(ns ingredient-lookup.blacklist)

(def makeup-blacklist
  ;; Ingredients you should avoid in cosmetics if pregnant
  #{"aluminum chloride hexahydrate"
    "aluminium chlorohydrate"
    "beta hydroxy acids"
    "chemical sunscreens"
    "salicylic acid"
    "3-hydroxypropionic acid"
    "trethocanic acid"
    "tropic acid"
    "avobenzone"
    "homosalate"
    "octisalate"
    "octocrylene"
    "oxybenzone"
    "oxtinoxate"
    "menthyl anthranilate"
    "oxtocrylene"
    "diethanolamine"
    "oleamide dea"
    "lauramide dea"
    "cocamide dea"
    "dihydroxyacetone"
    "dha"
    "formaldehyde"
    "quaternium-15"
    "dimethyl-dimethyl"
    "dmdm"
    "hydantoin"
    "imidazolidinyl urea"
    "diazolidinyl urea"
    "sodium hydroxymethylglycinate"
    "2-bromo-2-nitropropane-1,3-diol"
    "bromopol"
    "hydroquinone"
    "idrochinone"
    "quinol/1-4 dihydroxy benzene/1-4 hydroxy benzene"
    "propyl parabens"
    "butyl parabens"
    "isopropyl parabens"
    "isobutyl parabens"
    "methyl parabens"
    "diethyl"
    "dibutyl"
    "phthalates"
    "retinol"
    "vitamin a"
    "retinoic acid"
    "retinyl palmitate"
    "retinaldehyde"
    "adapalene"
    "tretinoin"
    "tazarotene"
    "isotretinoin"
    "acetyl mercaptan"
    "mercaptoacetate"
    "mercaptoacetic acid"
    "thiovanic acid"
    "methylbenzene"
    "toluol"
    "antisal 1a"})