(ns ingredient-lookup.blacklist)

(def makeup-blacklist
  ;; Ingredients you should avoid in cosmetics if pregnant
  #{"mercaptoacetate"
    "propyl parabens"
    "thioglycolic acid"
    "idrochinone"
    "linalool"
    "tretinoin"
    "dha"
    "botulinum toxin"
    "diethyl"
    "chemical sunscreens"
    "di-n-butyl phthalate"
    "dibutyl"
    "phenoxyethanol"
    "polyethylene glycol"
    "isobutyl parabens"
    "isopropyl parabens"
    "myreth"
    "dmdm hydantoin"
    "dysport"
    "sodium lauryl sulfate"
    "methicone"
    "peg"
    "polyoxyethylene"
    "eugenol"
    "ethyl"
    "quaternium-15"
    "mea"
    "ceteareth"
    "citronellol"
    "limonene"
    "adapalene"
    "petroleum"
    "diazolidinyl urea"
    "oxybenzone"
    "isobutylparabens"
    "vitamin a"
    "isopropyl"
    "octisalate"
    "fragrance"
    "methenamine"
    "oxtocrylene"
    "parfum"
    "botox"
    "tropic acid"
    "bpa"
    "beta hydroxy acids"
    "retinyl palmitate"
    "oleamide dea"
    "oxtinoxate"
    "quinol/1-4 dihydroxy benzene/1-4 hydroxy benzene"
    "retinyl linoleate"
    "aluminium chlorohydrate"
    "toluol"
    "diaminobenzene"
    "petrolatum"
    "glycyrrhizin"
    "imidazolidinyl urea"
    "coconut oil amide of diethanolamine"
    "diethanolamine"
    "perfume"
    "octocrylene"
    "aminophenol"
    "dihydroxyacetone"
    "3-hydroxypropionic acid"
    "dea"
    "2-bromo-2-nitropropane-1,3-diol"
    "propylene glycol"
    "diethyl phthalate"
    "bromopol"
    "propyl"
    "polyethylene"
    "methylbenzene"
    "bexarotene"
    "quarternium-15"
    "ppg"
    "trethocanic acid"
    "parabens"
    "oleth"
    "petroleum oil jelly"
    "coco diethanolamide"
    "laureth"
    "dmdm"
    "monoethanolamide"
    "isopropyl alcohol"
    "hydroquinone"
    "sulfates"
    "lauric diethanolamide"
    "retinoids"
    "acetyl mercaptan"
    "lauroyl diethanolamide"
    "stearic acid"
    "menthyl anthranilate"
    "geraniol"
    "butyl parabens"
    "lauramide dea"
    "retinal dehyde"
    "phenylenediamine"
    "sodium hydroxymethylglycinate"
    "methyl parabens"
    "homosalate"
    "dimethyl-dimethyl"
    "triethanolamine"
    "retinol"
    "benzene derivatives"
    "phthalate"
    "benzoyl peroxide"
    #_"eth"
    "salicylic acid"
    "hydantoin"
    "thiovanic acid"
    "mercaptoacetic acid"
    "avobenzone"
    "retinoic acid"
    "butyl"
    "tazarotene"
    "xeomin"
    "antisal 1a"
    "dbp"
    "alitretinoin"
    "tea"
    "cinnamal"
    "methoxysalicylate"
    "methyl"
    "mineral oil"
    "oxynol"
    "siloxane"
    "formaldehyde"
    "cocamide dea"
    "oral salicylic acid"
    "lauryl diethanolamide"
    "isotretinoin"
    "aluminum chloride hexahydrate"}
  )